default_platform(:ios)

APP_NAME = "CICDPoC"
APP_PROJECT_NAME = "CICDPoC.xcodeproj"
APP_WORKSPACE_NAME = "CICDPoC.xcworkspace"

APP_RELEASE_SCHEME = "CICDPoC"

DEVELOPER_APP_ID = ENV["DEVELOPER_APP_ID"]
DEVELOPER_APP_IDENTIFIER = ENV["DEVELOPER_APP_IDENTIFIER"]
PROVISIONING_PROFILE_SPECIFIER = ENV["PROVISIONING_PROFILE_SPECIFIER"]

APPLE_ISSUER_ID = ENV["APPLE_ISSUER_ID"]
APPLE_KEY_ID = ENV["APPLE_KEY_ID"]
APPLE_KEY_CONTENT = ENV["APPLE_KEY_CONTENT"]

TEMP_KEYCHAIN_USER = ENV["TEMP_KEYCHAIN_USER"]
TEMP_KEYCHAIN_PASSWORD = ENV["TEMP_KEYCHAIN_PASSWORD"]
GIT_AUTHORIZATION = ENV["GIT_AUTHORIZATION"]

def delete_temp_keychain(name)
  delete_keychain(
    name: name
  ) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
end

def create_temp_keychain(name, password)
  create_keychain(
    name: name,
    password: password,
    unlock: false,
    timeout: 0
  )
end

def ensure_temp_keychain(name, password)
  delete_temp_keychain(name)
  create_temp_keychain(name, password)
end

platform :ios do
  lane :release do
    skip_docs

    # Checking if required environment variables exist
    ensure_env_vars(
      env_vars: ['DEVELOPER_APP_ID', 
                 'DEVELOPER_APP_IDENTIFIER', 
                 'PROVISIONING_PROFILE_SPECIFIER', 
                 'APPLE_ISSUER_ID', 
                 'APPLE_KEY_ID', 
                 'APPLE_KEY_CONTENT', 
                 'TEMP_KEYCHAIN_USER', 
                 'TEMP_KEYCHAIN_PASSWORD', 
                 'GIT_AUTHORIZATION']
    )

    keychain_name = TEMP_KEYCHAIN_USER
    keychain_password = TEMP_KEYCHAIN_PASSWORD
    ensure_temp_keychain(keychain_name, keychain_password)

    api_key = app_store_connect_api_key(
      key_id: APPLE_KEY_ID,
      issuer_id: APPLE_ISSUER_ID,
      key_content: APPLE_KEY_CONTENT,            
      duration: 1200,            
      in_house: false
    )
    
#    increment_build_number(xcodeproj: "#{APP_PROJECT_NAME}")
    
    cocoapods(
      clean_install: true
    )

    match(
      type: 'appstore',
      app_identifier: "#{DEVELOPER_APP_IDENTIFIER}",
      git_basic_authorization: Base64.strict_encode64(GIT_AUTHORIZATION),
      readonly: true,
      keychain_name: keychain_name,
      keychain_password: keychain_password,
      api_key: api_key
    )

    gym(
      configuration: "Release",
      workspace: "#{APP_WORKSPACE_NAME}",
      scheme: "#{APP_RELEASE_SCHEME}",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: { 
            DEVELOPER_APP_ID => PROVISIONING_PROFILE_SPECIFIER
        }
      }
    )

    scan(
      workspace: "#{APP_WORKSPACE_NAME}",
      devices: ["iPhone 12"]
    )

    pilot(
      apple_id: "#{DEVELOPER_APP_ID}",
      app_identifier: "#{DEVELOPER_APP_IDENTIFIER}",
      skip_waiting_for_build_processing: true,
      skip_submission: true,
      distribute_external: false,
      notify_external_testers: false,
      ipa: "./#{APP_NAME}.ipa"
    )

    delete_temp_keychain(keychain_name)
  end
end